### ISSUE TITLE
Framework for Recommender

### ISSUE THREAD

**Issue by Floor97** [ChrisSBras/trustchain-superapp#14]
- [x] Implement an algorithm for sorting the list of profiles based on recommender.
- [x] Keeping track of watched/unwatched videos.

**Comment by junojense** [comment]
Suggestion is to use custom comparators for the sorting algorithm, I kind of already added this to my previous branch

**Comment by junojense** [comment]
The current torrent files are stored as `mutableListOf<TorrentHandler>()`, this contains all videos. Meanwhile, profile is stored as `HashMap<String, ProfileEntry> = HashMap()` which contains all the watched videos. Perhaps we want to change `String` to `TorrentHandler` here, such that we can use the subtract function in Kotlin to create a set of unwatched videos.

- [ ] Rework `HashMap<String, ProfileEntry>` to `HashMap<TorrentHandler, ProfileEntry>`
- [ ] Create a skeleton file `Predictor.kt` which specifies the unwatched videos

**Comment by junojense** [comment]
Is there any other functionality that should be part of this issue?
