### ISSUE TITLE
Profile metrics

### ISSUE THREAD

**Issue by Floor97** [ChrisSBras/trustchain-superapp#23]
- [x] Accurate watch time (instead of relative time)
- [x] Duration
- [x] Other metrics from video adapter 
- [x] Upvotes, possibly branch from pr if it is still not merged
- [x] Number of shares for torrent, like a hashmap where you can lookup torrent hash and get a number for the amount of times you have received this same torrent (`HashMap<String,Int>`) (probably easy to do in `addTorrent` in the torrent manager where it is checked if you have received a torrent before).
- [x] Hopcount of torrent: so every time a torrent is sent the hopcount is +1.
- [x]  Watched: boolean, to distinguish watched and unwatched videos (the current watched and unwatched methods don't do the right thing, since videos in the profiles list don't have to be watched to be in there).
- [x] Upload time

**Comment by junojense** [comment]
Cap the max viewtime (x10 duration)
