### ISSUE TITLE
Debug Screen

### ISSUE THREAD

**Issue by ChrisSBras** [ChrisSBras/trustchain-superapp#25]
The debug screen should show 

- [x]  Estimated networksize
- [x]  #connected peers
- [x] List of connected peer, and per peer last numbers of ip/mid
- [ ] Top 3 leeching torrents with metrics from leechers
- [ ] Top 3 seeding torrents with metrics from seeders
- [x] Seeding status
- [x] Wallet token amount
- [x] Peer ID (mid)

**Comment by Floor97** [comment]
Top 3 leeching is in torrentFiles, from currentIndex, first 3
Top 3 is first 3 of seedingTorrents list
