### ISSUE TITLE
Coin Toss Recommender

### ISSUE THREAD

**Issue by Floor97** [ChrisSBras/trustchain-superapp#7]
Skeleton recommender 50/50 coin toss, for future yield prediction.

depends on: #5

**Comment by junojense** [comment]
Idea is to build a function that takes as an input a list of magnet links (with associated tags?) and output a single magnet link based on a random number

**Comment by junojense** [comment]
The depth/direction of the recommender is unclear. How do we obtain certain properties (e.g. "the video is about cats") from a video when they upload it without explicitly asking for this from the user. Or, do we want to build a recommendation system based on the taste buddy concept where users are grouped in virtual communities based on their interests? 

Also, it's hard to find the properties or signs that a video might go viral. Say, a two new videos are uploaded and they get the tags "cat" and "wall" respectively. Now, another user might see these two videos, and will somehow have to decide which of the tags might be better to invest in. 

Alternatively, maybe we can make some social distance metric between users and see whether this video might be popular in its local clique of people with similar interests. 

Kind of a chaotic comment but I'm just writing out thoughts :)

**Comment by junojense** [comment]
Discussed with Pouwelse to structure the recommendation profile as a list of magnet links with some parameters stuck to it (watching time, engagement(?), freshness(?)) and to see whether we can get anything to work which is better than coin toss. The input to the recommender should thus not be a list of magnet links but a list of profiles and a basic class for the profile should be added.

**Comment by junojense** [comment]
See comments in the pull request for how this issue was implemented and what we should do next
