### ISSUE TITLE
Progress bar for download swarms

### ISSUE THREAD

**Issue by ChelseaGuan** [ChrisSBras/trustchain-superapp#9]
A progress bar should be displayed when a peer is downloading a video.
Can be done using DHT bootstrapped, number of discovered peers, got .torrent, first MByte, PEX peers, etc. 
Use big test swarms, the goal is for the user to feel their phone is working very hard.

**Comment by ChelseaGuan** [comment]
Implemented *extremely* basic progress bar using multithreading and dummy data. Currently, it is not linked to download progress since the progress bar is created in the onCreate() function of `DeToksMainActivity.kt`, but I am having trouble accessing download data required from `TorrentManager.kt`.

**Comment by synctext** [comment]
Example: 
https://thumbs.dreamstime.com/b/set-simple-step-step-progress-bar-vector-ui-elements-eps-32100102.jpg

**Comment by ChelseaGuan** [comment]
Progress bar now shows the number of connected peers.
It seems that the progress bar UI does not update when the code is in the GossiperService class, but works in the DeToksMainActivity class, might have something to do with which classes can create UI components. Code is also quite buggy right now, the videos do not load, and the progress bar only updates if the user leaves the detoks subapp and clicks back into it.

**Comment by ChelseaGuan** [comment]
Moved the progress bar to VideoAdapter, videos load now. Got the number of peers to be updated whenever a user scrolls a video, but it still does not update continuously. PR #141 Tribler/trustchain-superapp also has issues making UI update on the fly. 
Also looked into incorporating musicdao's debugging screen into detoks.

**Comment by ChelseaGuan** [comment]
Thanks to the postDelayed method also used in #21, the text displaying the number of peers connected now updates in real-time. Currently, it displays over the video being played like this:
![display_nb_peers](https://user-images.githubusercontent.com/57201085/229313682-fee6ac28-6374-48d2-a28e-05a8cd91bc62.PNG)
